name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Set version from tag
        run: |
          TAG="${GITHUB_REF_NAME}"
          VERSION=${TAG#v}
          echo "Setting package.json version to ${VERSION}"
          yarn version --no-git-tag-version --new-version "${VERSION}"

      - name: Build
        run: yarn build

      - name: Configure npm auth for Yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          yarn config set registry "https://registry.npmjs.org"

      - name: Publish
        run: yarn publish --access public --non-interactive
